services:
  backend:
    build: ./backend
    container_name: tz-backend
    image: tz-backend:v1.0
    networks:
      - tz-network
    expose:
      - "8080"

  nginx:
    image: nginx:1.30.2-alpine
    container_name: tz-nginx
    volumes:
      # Separate config file according to assignment
      - ./nginx/nginx.conf:/etc/nginx/conf.d/tz.conf:ro
      # Suppress default config
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tz-network
    ports:
      - "127.0.0.1:80:80"
    depends_on: 
      - backend

networks:
  tz-network:
    driver: bridge
    name: tz-network
